travis:
  secure:
    BINSTAR_TOKEN: PlxPDKbha7JQmOOsx46NA30V3VtoMbY+RNAjTBbcOkGxA0sZj69nbAdDAaLdQXB4nA6hMJceAtMKaTkP0CN0vCXqG+mSn/gz3w22XrvoFv1R5fHACfeRrAspaKHZbiIjTCI3+6zbxLaHXhQliHKUGzz20o5KFc+E/YzQU9mf3QlmENJ2daVQsmEUkTmZlL+AA/wZjLAsrVweXHjtW1qwkhuocnN216eBIVrwfNnpxY73H9fNYHLZ87FXXDZTtT6qzReYKi1FhW8XffTznSV3E4MVLgo7EC7KzgoYhoOyqkPzInB6D1Li2l3Vvug5egnoEMPcFEz6mKxeIuRRwuPIjbrC9Ahdekn7tAWj8+6jt17M5hsph77ClPGoUPjYzSpq6FKbdLTyKxhrH2SHr25im1x1CYGD0N+eqgHbMETUt0bx2//j1FYj7Ap7QShPa14PnP2iWVXYcTh2D5tKsxc6cR1sF+2YeY6hQowJu5boxKkLKQJbLpZWEfU82Blv5b5sII9AlZM/lOLh7qSOp0Ben8NfzhC8ENhV5vi9NfT7/5feaX3OH0+3e+OmXWk0xCESJbTv2ZUQUzx02pZsjFLLni5vN9ofaFmTi79xxjqjUGeG3YNjiF+lzWqG6b1fvJPLMdfZr9fZuiEAy0Y7RpxoYZB5TqbNHa31luDqF8kbr7g=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
